spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
    username: postgres.rljldvpboqapokzecfff
    password: ho_hu_li_li_
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Keep existing data
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: true
  flyway:
    enabled: false  # Disable Flyway for dev to avoid migration issues

server:
  port: 8088
